 name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello World"
